/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bba13d373b0556425d5c848ba3039956)
interface __BaseEnv_Env {
	LEVELS_DB: D1Database;
	ADMIN_PASSWORD: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_PASSWORD">> {}
}
